name: Report a bug
description: Report a bug
title: '[Bug]: '
labels:
  - bug
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what happened
    validations:
      required: true
  - type: textarea
    id: what-should-happened
    attributes:
      label: 'What should have happened?'
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: LOG
      description: If you have log, please send it to us!
  - type: checkboxes
    attributes:
      label: I read the Code Of Conduct
      options:
        - label: I read the Code Of Conduct and I comply to it
          required: true
