name: Engine testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Install CMake
      run: sudo apt-get install -y cmake build-essential

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install CSFML
      run: ./Scripts/install_csfml.sh

    - name: Install Criterion
      run: sudo apt-get install libcriterion-dev

    - name: Build engine
      run: make build_tests

    - name: Testing engine
      run: make run_tests
