name: Server Client CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install Python dev packages
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev

    - name: Install CMake
      run: |
        sudo apt-get install -y cmake
        sudo apt-get install -y build-essential

    - name: Checkout
      uses: actions/checkout@v2

    - name: Install CSFML
      run: ./build/install_csfml.sh

    - name: make share server client
      run: make share server client

    - name: SonarCloud Scan for C and C++
      uses: SonarSource/sonarcloud-github-c-cpp@v1.3

    - name: Check if build succeeded
      run: exit $(($? != 0))
