name: Engine testing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Install CMake
      run: |
        sudo apt-get install cmake
        sudo apt-get install build-essential

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install CSFML
      run: ./build/install_csfml.sh

    - name: Install Criterion
      run: ./build/install_criterion.sh

    - name: Testing
      run: ./run_test.sh -e
